version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    restart: always
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build: .
    container_name: fastapi_ChatGPT_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourPassword123@db:1433/finance_simulator?driver=ODBC+Driver+17+for+SQL+Server"
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - .:/app

networks:
  app_network:

volumes:
  sqlserver_data:
