version: "3.8"
services:
  app2:
    image: back-app-gemini
    build: .
    container_name: fastapi_Gemini_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: YourPassword123
      DB_NAME: YourDatabaseName
      DB_DRIVER: ODBC Driver 17 for SQL Server
    # depends_on:
    #   - db

  # db:
  #   image: sua_imagem_sqlserver # Substitua pela imagem do seu SQL Server
  #   ports:
  #     - "1434:1433"
  #   environment:
  #     SA_PASSWORD: YourPassword123
  #     ACCEPT_EULA: "1"