version: '3.9'

services:
  # db:
  #   image: mcr.microsoft.com/mssql/server
  #   container_name: sql_server
  #   environment:
  #     SA_PASSWORD: "YourPassword123"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1434:1433"

  web:
    build: .
    container_name: fastapi_Copilot_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
